version: '3.8'

services:
  api-server:
    image: ghcr.io/Stockone19/server-app:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # worker-server:
  #   image: ghcr.io/your-org/investment-backend-worker:latest
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-server
      # - worker-server
    restart: unless-stopped