services:
  api-server:
    image: ${IMAGE_NAME:-ghcr.io/stockone19/server-app:latest}
    container_name: api-server
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - app-network

  data-server:
    image: ${IMAGE_NAME:-ghcr.io/stockone19/stock-app:latest}
    container_name: data-server
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-server
      - data-server
    restart: unless-stopped
    networks:
      - app-network

  redis-server:
    image: redis:7-alpine
    container_name: redis-server
    volumes:
      - /tmp/redis:/data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge