version: '3.8'

services:
  api-server:
    image: ${IMAGE_NAME:-ghcr.io/stockone19/server-app:latest}
    container_name: api-server
    ports:
      - "8081:8081"
    restart: unless-stopped

  data-server:
    image: ${IMAGE_NAME:-ghcr.io/stockone19/stock-app:latest}
    container_name: data-server
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-server
      - data-server
    restart: unless-stopped

  redis-server:
    image: redis:7-alpine
    container_name: redis-server
    volumes:
      - ./redis-data:/data
